# NeuralRetail - Data Cleaning & EDA

In [15]:
pip install pandas numpy matplotlib seaborn plotly scikit-learn openpyxl jupyter

Requirement already satisfied: pandas in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (2.4.1)
Requirement already satisfied: matplotlib in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (0.13.2)
Requirement already satisfied: plotly in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (6.7.0)
Requirement already satisfied: scikit-learn in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (1.8.0)
Requirement already satisfied: openpyxl in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (3.1.5)
Requirement already satisfied: jupyter in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (1.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from plotly) (2.21.0)
Requirement already satisfied: scipy>=1.10.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: et-xmlfile in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: notebook in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter) (7.5.6)
Requirement already satisfied: jupyter-console in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipykernel in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from jupyter) (7.1.0)
Requirement already satisfied: ipywidgets in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter) (8.1.8)
Requirement already satisfied: jupyterlab in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter) (4.5.7)
Requirement already satisfied: six>=1.5 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (9.9.0)
Requirement already satisfied: jupyter-client>=8.0.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.2 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (6.5.4)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.5.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel->jupyter) (0.8.5)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.5.1)
Requirement already satisfied: executing>=1.2.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\jiten\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from ipywidgets->jupyter) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from ipywidgets->jupyter) (3.0.16)
Requirement already satisfied: async-lru>=1.0.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (2.18.2)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab->jupyter) (80.10.2)
Requirement already satisfied: anyio in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.13.0)
Requirement already satisfied: certifi in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.1.4)
Requirement already satisfied: httpcore==1.* in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.25.0)
Requirement already satisfied: pywinpty>=2.0.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: send2trash>=1.8.2 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: babel>=2.10 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: requests>=2.31 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.32.5)
Requirement already satisfied: typing_extensions>=4.5 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (4.15.0)
Requirement already satisfied: argon2-cffi-bindings in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.30.0)
Requirement already satisfied: python-json-logger>=2.0.4 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbconvert->jupyter) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.3.0)
Requirement already satisfied: defusedxml in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbconvert->jupyter) (3.2.1)
Requirement already satisfied: nbclient>=0.5.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbconvert->jupyter) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.8.3)
Requirement already satisfied: arrow>=0.15.0 in d:\Apps\Coding Languages\Python 3.12.10\Lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.4.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

# Load both sheets
df_2009 = pd.read_excel(
    '../data/raw/online_retail_II.xlsx',
    sheet_name='Year 2009-2010'
)

df_2010 = pd.read_excel(
    '../data/raw/online_retail_II.xlsx',
    sheet_name='Year 2010-2011'
)

# Combine datasets
df = pd.concat([df_2009, df_2010], ignore_index=True)

# Check shape
print(df.shape)

# Preview
df.head()

(1067371, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [18]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

## Remove Missing Customer IDs

In [19]:
df = df.dropna(subset=['Customer ID'])

## Remove Missing Descriptions

In [20]:
df = df.dropna(subset=['Description'])

## Remove Negative Quantities

In [21]:
df = df[df['Quantity'] > 0]

## Remove Invalid Prices

In [22]:
df = df[df['Price'] > 0]

In [23]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [24]:
print(df.shape)

(805549, 8)

In [25]:
df = df.drop_duplicates()

In [26]:
print(df.shape)

(779425, 8)

In [27]:
df['Customer ID'] = df['Customer ID'].astype(int)

In [28]:
df['TotalAmount'] = df['Quantity'] * df['Price']

In [29]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['MonthName'] = df['InvoiceDate'].dt.month_name()
df['Quarter'] = df['InvoiceDate'].dt.quarter
df['Weekday'] = df['InvoiceDate'].dt.day_name()
df['Hour'] = df['InvoiceDate'].dt.hour

In [30]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount,Year,Month,MonthName,Quarter,Weekday,Hour
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,December,4,Tuesday,7
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,December,4,Tuesday,7
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,December,4,Tuesday,7
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,December,4,Tuesday,7
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,December,4,Tuesday,7

In [33]:
print(df.shape)

(779425, 15)

In [31]:
df.to_csv('../data/processed/cleaned_retail_data.csv', index=False)

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[us]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  int64
 7   Country      779425 non-null  str
 8   TotalAmount  779425 non-null  float64
 9   Year         779425 non-null  int32
 10  Month        779425 non-null  int32
 11  MonthName    779425 non-null  str
 12  Quarter      779425 non-null  int32
 13  Weekday      779425 non-null  str
 14  Hour         779425 non-null  int32
dtypes: datetime64[us](1), float64(2), int32(4), int64(2), object(3), str(3)
memory usage: 83.3+ MB

In [35]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,TotalAmount,Year,Month,Quarter,Hour
count,779425.000000,779425,779425.000000,779425.000000,779425.000000,779425.000000,779425.000000,779425.000000,779425.000000
mean,13.489370,2011-01-03 01:44:42.593476,3.218488,15320.360461,22.291823,2010.432051,7.417059,2.796884,12.791884
min,1.000000,2009-12-01 07:45:00,0.001000,12346.000000,0.001000,2009.000000,1.000000,1.000000,6.000000
25%,2.000000,2010-07-02 14:39:00,1.250000,13971.000000,4.950000,2010.000000,5.000000,2.000000,11.000000
50%,6.000000,2010-12-02 14:09:00,1.950000,15247.000000,12.480000,2010.000000,8.000000,3.000000,13.000000
75%,12.000000,2011-08-01 13:44:00,3.750000,16794.000000,19.800000,2011.000000,11.000000,4.000000,14.000000
max,80995.000000,2011-12-09 12:50:00,10953.500000,18287.000000,168469.600000,2011.000000,12.000000,4.000000,20.000000
std,145.855814,NaN,29.676140,1695.692775,227.427075,0.568385,3.422319,1.132107,2.294182